### ISSUE TITLE
Can't specify multiple APK include filters

### ISSUE THREAD

**Issue by DSteve595** [bitrise-steplib/steps-gradle-runner#60]
In my project, I'm building an app bundle (.aab) and an APK. I'm trying to have them both be picked up (`*.aab` and `*.apk`) in the APK path list, but it looks like I can't add multiple options to the APK include filter. This is supported in the exclude filter, and it adds multiple `! -path` arguments to `find`, but it doesn't seem to work for the include filter.

**Comment by BirmacherAkos** [comment]
Hi @DSteve595 !

Thanks for the report 🥇 
I've created a card for the Tooling Team.

**Comment by DSteve595** [comment]
Appreciate the response!

>If you want to do this on your local machine via ./gradlew command you would need to run it multiple time

This isn't true, `./gradlew assembleRelease bundleRelease` is a perfectly valid command that will produce both an APK and an AAB.

**Comment by DSteve595** [comment]
👋

**Comment by fehersanyi-bitrise** [comment]
Hy @DSteve595 

I understand the concept, but maybe the step can't handle it like this, I would suggest using 2 gradle runner steps after another and run the 2 commands separately, and in the bundleRelease version change the export options from apk to aab

**Comment by sophiataskova** [comment]
@DSteve595 now you should be able to, using app_file_include_filter

**Comment by DSteve595** [comment]
Thanks so much!
