### ISSUE TITLE
Is there any way to provide specific folder pattern to search for APK and AAB?

### ISSUE THREAD

**Issue by amatkivskiy** [bitrise-steplib/steps-gradle-runner#67]
Hi all,

Recently our team has switched to Google Play deployment using Android Bundles. For that to implement throw CI flow we needed to export `*.aab` files. We figured out that during build process gradle produces multiple `.aab` files (not only in output directory but also intermediate bundles in  `/build/intermediates/intermediary_bundle/_build_variant_name/`). This causes step to deploy wrong `.aab` file. 
 
So seems it will be nice to specify folder path under which step should find proper artifacts like `/build/outputs/*.aab`. Is this possible?

**Comment by bitce** [comment]
Hi @amatkivskiy! That is also an option, but alternatively, you can specify the wanted type of .aab-s in the include filter

**Comment by amatkivskiy** [comment]
@bitce  Can you please specify an example ?

**Comment by guness** [comment]
I am also experiencing same issue.
both file names are same, they are just in different directories.
