### ISSUE TITLE
Cached builds failing with Gradle 6.5 

### ISSUE THREAD

**Issue by G00fY2** [bitrise-steplib/steps-gradle-runner#75]
Since this topic got no attention in the slack channel or on discuss.bitrise.io I want to report this over here:

We recently updated to latest Gradle version 6.5 in most of our Android projects. Unfortunately the builds on bitrise started crashing. There seems to be an issue with the Gradle caching.
    
    A problem occurred configuring project ':app'.
    > Expected a single classpath entry, found: []
    ...
    Caused by: java.lang.IllegalStateException: Expected a single classpath entry, found: []
        at org.gradle.groovy.scripts.internal.FileCacheBackedScriptClassCompiler.remapClasses(FileCacheBackedScriptClassCompiler.java:153)

This only occurs on bitrise.io. We have no issues building locally. Also projects on Travis CI (with the same logic) are running fine. Downgrading to Gradle 6.4.1 fixes the issue.

Here is sample project:

I tried several scenarios (some as close as possible as our Travis CI setups) but all are failing. Each time when I changed the workflow I cleared the cache, so the first build after that runs fine.
1. ([build #43](https://app.bitrise.io/build/48b7925349332acd#?tab=log))
* Pull Cache Task
* Gradle Runner Task with caching set to "none"
* Gradle Push Task to upload the Gradle cache folder, ignoring recommended files from cache

2. ([build #45](https://app.bitrise.io/build/e605450f81707cc8#?tab=log))
* Pull Cache Task
* Gradle Runner Task with caching set to "none"
* Bash script to delete recommended files from cache
* Gradle Push Task to upload the Gradle cache folder

3. ([build #47](https://app.bitrise.io/build/7f77c929b0c7c17f#?tab=log))
* Pull Cache Task
* Gradle Runner Task with caching set to "all"
* Gradle Push Task default parameters

4. [Travis CI build for the same project running fine using the cache](https://travis-ci.com/github/G00fY2/android-ci-testproject/builds/169634502) (expected build #45 to behave exactly the same)

Any idea what the issue could be?

**Comment by G00fY2** [comment]
FYI I also created an issue in the Gradle repo: https://github.com/gradle/gradle/issues/13367#issuecomment-641169508

**Comment by non-binary** [comment]
Hi @G00fY2,

Thank you for reaching out.

It seems you resolved the problem in the Gradle issue?

**Comment by G00fY2** [comment]
Looks like this issue was caused by the bitrise cache-push step, which ignored empty cache directories. This was fixed with the cache-push [2.3](https://github.com/bitrise-steplib/steps-cache-push/releases/tag/2.3.0) and will be addressed by the [Gradle team with Gradle 6.6](https://github.com/gradle/gradle/issues/13367).
