### ISSUE TITLE
Setting JAVA 11 doesn't change jdk used by Gradle Runner

### ISSUE THREAD

**Issue by hinewwiner** [bitrise-steplib/steps-gradle-runner#80]
I use "Do anything with script" step to set JAVA 11 as follows.

`#!/bin/bash
set -ex
   
add-apt-repository -y ppa:openjdk-r/ppa
apt-get update -qq
apt-get install -y openjdk-11-jdk
update-java-alternatives -s /usr/lib/jvm/java-1.11.0-openjdk-amd64
JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export JAVA_HOME
echo "done"`

When I run a task with Gradle Runner, I still get warnings saying JAVA 1.8 is deprecated.
`> Task :app:sonarqube
The version of Java (1.8.0_265) you have used to run this analysis is deprecated and we will stop accepting it from October 2020. Please update to at least Java 11.
`

Is there any option that I need to change to make Gradle work with Java 11?

**Comment by mjones-droid** [comment]
Hey @hinewwiner! It looks like you're not using envman to change the value of JAVA_HOME. Please follow the instructions here for setting up Java 11. 

https://devcenter.bitrise.io/infrastructure/virtual-machines/#switching-to-java-11
