### ISSUE TITLE
gradle-runner 1.9.8 - Step always fail

### ISSUE THREAD

**Issue by fedesenmartin** [bitrise-steplib/steps-gradle-runner#86]
### Troubleshooting

- [ ] I've searched [discuss.bitrise.io](https://discuss.bitrise.io/) for possible solutions.
- Which version of the step is effected? 1.9.8
- Is the issue reproducible with the latest version? YES 
- Does the issue happen sporadically, or every time? EVERY TIME
- Is the issue reproducible locally by following our [local debug guide](https://devcenter.bitrise.io/troubleshooting/debugging-your-build-on-your-own-machine/)? YES

### Useful information

- [FAQ](https://devcenter.bitrise.io/faq/faq-index/)
- [devcenter.bitrise.io](https://devcenter.bitrise.io/)

### Bitrise info

- Build URL: app.bitrise.io/build/61e73fc2051659b0
- [Bitrise Support](https://devcenter.bitrise.io/troubleshooting/enabling-bitrise-support-user/) enabled: _YES / NO_
- Log: [21:42:29] Step (gradle-runner) failed: Failed to prepare the step for execution through the required toolkit (go), error: Failed to install package, error: exit status 2 

<details>
  <pre>
+------------------------------------------------------------------------------+

| (8) gradle-runner                                                            |
+------------------------------------------------------------------------------+
| id: gradle-runner                                                            |
| version: 1.9.8                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: go                                                                  |
| time: 2021-06-02T21:42:28Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
# github.com/bitrise-io/steps-gradle-runner/vendor/github.com/hashicorp/go-cleanhttp
src/github.com/bitrise-io/steps-gradle-runner/vendor/github.com/hashicorp/go-cleanhttp/cleanhttp.go:35:3: unknown field 'ForceAttemptHTTP2' in struct literal of type http.Transport
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | gradle-runner (exit code: 1)                                  | 2.49 sec |
+---+---------------------------------------------------------------+----------+
ERRO[21:42:29] Step (gradle-runner) failed: Failed to prepare the step for execution through the required toolkit (go), error: Failed to install package, error: exit status 2 
| Issue tracker: https://github.com/bitrise-io/steps-gradle-runner/issues      |
| Source: https://github.com/bitrise-io/steps-gradle-runner                    |
+---+---------------------------------------------------------------+----------+
  </pre>
</details>

### Steps to reproduce

1. Update gradle-runner to 1.9.8 version
2. gradle-runner step will fail with error 

### Fix 
Downgrade to 1.9.7

**Comment by lpusok** [comment]
Hello @fedesenmartin,
Sorry for the caused inconvenience. Please update to the Ubuntu 20.04 stack (or the non LTS Ubuntu 16.04 stack). Ubuntu 16.04 stacks still continue to work but are deprecated and are planned to be removed.

**Comment by fedesenmartin** [comment]
Hi @lpusok 
Updating stack to 20.04 & using gradle-runner 1.9.8 works fine!
